### ISSUE TITLE
Probably not your issue but I need your help

### ISSUE THREAD

**Issue by DummyHS** [ugraveknight/Healslut-Master#5]
I tried instaling and setting up the application. But I just cant seem to get the window to open. I tried both running the HealslutMaster.py file and launching it from powershell. I really dont know what I did wrong and tried solving it on my own. I would really appreciate the help. I am on W10 64bit, and this is what powershell wrote(after ctrl+c):

PS C:\Users\dada\Desktop\Healslut-Master-1.4.4> PS C:\Users\dada\Desktop\Healslut-Master-1.4.4> python HealslutMaster.py
>> if you believe this program has frozen, press ctrl + c, then check the Errors folder for details
>> Version number: v1.4.3
>> A new version is available! Visit: https://github.com/ugraveknight/Healslut-Master/releases
>> healslutmaster.init Error list index out of range
>> handleError Error [Errno 2] No such file or directory: 'Resources\\Errors\\healslutmaster.init.txt'
>> healslutmaster.go Error [Errno 2] No such file or directory: 'Resources\\Errors\\handleError.txt'
>> handleError Error [Errno 2] No such file or directory: 'Resources\\Errors\\healslutmaster.go.txt'
>> Traceback (most recent call last):
>>   File "HealslutMaster.py", line 100, in __init__
>>     self.SetupVars(background_list,prefdict,hyp_folders)
>>   File "HealslutMaster.py", line 120, in SetupVars
>>     self.background_select.set(background_list[self.background_select_var])
>> IndexError: list index out of range
>>
>> During handling of the above exception, another exception occurred:
>>
>> Traceback (most recent call last):
>>   File "C:\Users\dada\Desktop\Healslut-Master-1.4.4\HealslutPackages.py", line 62, in handleError
>>     handlewriter(tb, e, func, subj='')
>>   File "C:\Users\dada\Desktop\Healslut-Master-1.4.4\HealslutPackages.py", line 59, in handlewriter
>>     with open(file, 'a') as f:
>> FileNotFoundError: [Errno 2] No such file or directory: 'Resources\\Errors\\healslutmaster.init.txt'
>>
>> During handling of the above exception, another exception occurred:
>>
>> Traceback (most recent call last):
>>   File "HealslutMaster.py", line 1283, in go
>>     e = HealslutMaster(root,  GenFolders(), genuserinfo(), GenBackgroundList(), genuserpref())
>>   File "HealslutMaster.py", line 106, in __init__
>>     handleError(format_exc(2), e, 'healslutmaster.init', subj='')
>>   File "C:\Users\dada\Desktop\Healslut-Master-1.4.4\HealslutPackages.py", line 64, in handleError
>>     handlewriter(tb, e, 'handleError', subj='')
>>   File "C:\Users\dada\Desktop\Healslut-Master-1.4.4\HealslutPackages.py", line 59, in handlewriter
>>     with open(file, 'a') as f:
>> FileNotFoundError: [Errno 2] No such file or directory: 'Resources\\Errors\\handleError.txt'
>>
>> During handling of the above exception, another exception occurred:
>>
>> Traceback (most recent call last):
>>   File "C:\Users\dada\Desktop\Healslut-Master-1.4.4\HealslutPackages.py", line 62, in handleError
>>     handlewriter(tb, e, func, subj='')
>>   File "C:\Users\dada\Desktop\Healslut-Master-1.4.4\HealslutPackages.py", line 59, in handlewriter
>>     with open(file, 'a') as f:
>> FileNotFoundError: [Errno 2] No such file or directory: 'Resources\\Errors\\healslutmaster.go.txt'
>>
>> During handling of the above exception, another exception occurred:
>>
>> Traceback (most recent call last):
>>   File "HealslutMaster.py", line 1291, in <module>
>>     go()
>>   File "HealslutMaster.py", line 1287, in go
>>     handleError(format_exc(2), e, 'healslutmaster.go', subj='')
>>   File "C:\Users\dada\Desktop\Healslut-Master-1.4.4\HealslutPackages.py", line 64, in handleError
>>     handlewriter(tb, e, 'handleError', subj='')
>>   File "C:\Users\dada\Desktop\Healslut-Master-1.4.4\HealslutPackages.py", line 59, in handlewriter
>>     with open(file, 'a') as f:
>> FileNotFoundError: [Errno 2] No such file or directory: 'Resources\\Errors\\handleError.txt'
>> PS C:\Users\dada\Desktop\Healslut-Master-1.4.4>

**Comment by DummyHS** [comment]
I tried reinstalling today, fresh download. However it wont start since it always fails to import module OWVibe. Dont know if that helps

**Comment by DummyHS** [comment]
Downloaded wrong file >,< all works now <3
